name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MY_ENV: CI

jobs:
  test-macos:
    strategy:
      matrix:
        os: [macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply granddaifuku --branch ${{ github.head_ref }}
      - name: Verify
        run: ./bin/chezmoi verify
  test-linux:
    strategy:
      matrix:
        image: ["fedora:39"]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Setup chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply granddaifuku --branch ${{ github.head_ref }}
      - name: Verify
        run: ./bin/chezmoi verify
    
